# Generated by Django 4.0.6 on 2022-08-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memtests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='css_file',
            field=models.FileField(upload_to='css_files'),
        ),
        migrations.AlterField(
            model_name='test',
            name='html_file',
            field=models.FileField(upload_to='html_files'),
        ),
        migrations.AlterField(
            model_name='test',
            name='js_file',
            field=models.FileField(upload_to='js_files'),
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
